### ISSUE TITLE
First video autoplays when search result appear

### ISSUE THREAD

**Issue by TangoMan75** [flazzarotto/kaamelott-videoboard#2]
Remove autoplay

**Comment by flazzarotto** [comment]
I cannot reproduce this, neither on FF, neither on Chrome, Ubuntu 20.04.

**Comment by flazzarotto** [comment]
OK, I got it. Vue components keep data in memory, but I manage to do it with the store (I changed the whole store anyway so that the state is read-only).

**Comment by flazzarotto** [comment]
Fixed in 611d70d46eba9df7a08237504369c803fb1e7fa7
